<a href="https://colab.research.google.com/github/scribenaz/CPP528/blob/main/Exercise_11_Shriver_Smith_GetDataFromKaggle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Shriver Smith  
Exercise 11  
Class: AIM111 - Introduction to Data Science  
Date: October 14, 2026

In [1]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "synthetic_traffic_benchmark_200k.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "razanihababdellatif/emergency-dispatch-and-traffic-physics-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/tmp/ipykernel_1296/1295576201.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Downloading to /root/.cache/kagglehub/datasets/razanihababdellatif/emergency-dispatch-and-traffic-physics-dataset/versions/1/synthetic_traffic_benchmark_200k.csv...

100%|██████████| 36.0M/36.0M [00:00<00:00, 38.0MB/s]

First 5 records:      Record_ID                      Timestamp        Date  Hour  Month  \
0  REC_0000000  2024-03-14 17:35:06.841829282  2024-03-14    17      3
1  REC_0000001  2023-05-25 08:10:56.398060108  2023-05-25     8      5
2  REC_0000002  2023-11-07 08:25:17.721608262  2023-11-07     8     11
3  REC_0000003  2024-07-24 09:30:00.947374674  2024-07-24     9      7
4  REC_0000004  2024-04-03 09:34:07.316651267  2024-04-03     9      4

  Day_of_Week   Time_of_Day  Is_Holiday Area_Type   Road_Type  ...  \
0    Thursday  Evening Peak           0     Urban  Interstate  ...
1    Thursday  Morning Peak           0  Suburban  Interstate  ...
2     Tuesday  Morning Peak           0  Suburban  Interstate  ...
3   Wednesday  Morning Peak           0  Suburban   Collector  ...
4   Wednesday  Morning Peak           0     Urban       Local  ...

  Vehicle_Age_yrs  Recorded_Speed_kmh Baseline_Expected_Response_Time_min  \
0             7.2                49.0                                 6.2
1             9.4                70.1                                15.0
2             2.9                71.9                                14.6
3             4.4                58.7                                13.2
4             1.8                25.4                                 7.8

  Accident_Occurred  Collision_Type  Vehicles_Involved Accident_Severity  \
0                 0             NaN                  0       No Accident
1                 0             NaN                  0       No Accident
2                 0             NaN                  0       No Accident
3                 0             NaN                  0       No Accident
4                 0             NaN                  0       No Accident

   Dispatch_Priority  Actual_Response_Time_min  Road_Closure_Duration_min
0                NaN                       0.0                        0.0
1                NaN                       0.0                        0.0
2                NaN                       0.0                        0.0
3                NaN                       0.0                        0.0
4                NaN                       0.0                        0.0

[5 rows x 29 columns]

In [2]:
import pandas as pd

## First Pair

Adding a cell so start with that calls the info() method of the DataFrame to display some information about its columns (29) and entries (200000), so we know what we are working with, column names, data type, Non-null count as that may be what we will be looking to clean up. We will also see how large this dataset is, and in this case a little of 44MB.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 29 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   Record_ID                            200000 non-null  object
 1   Timestamp                            200000 non-null  object
 2   Date                                 200000 non-null  object
 3   Hour                                 200000 non-null  int64
 4   Month                                200000 non-null  int64
 5   Day_of_Week                          200000 non-null  object
 6   Time_of_Day                          200000 non-null  object
 7   Is_Holiday                           200000 non-null  int64
 8   Area_Type                            200000 non-null  object
 9   Road_Type                            200000 non-null  object
 10  Intersection_Type                    131481 non-null  object
 11  Speed_Limit_kmh                      200000 non-null  int64
 12  Weather                              200000 non-null  object
 13  Road_Condition                       200000 non-null  object
 14  Visibility_m                         194907 non-null  float64
 15  Congestion_Index                     200000 non-null  float64
 16  Vehicle_Type                         200000 non-null  object
 17  Driver_Age                           200000 non-null  float64
 18  Driver_Experience_yrs                196004 non-null  float64
 19  Vehicle_Age_yrs                      200000 non-null  float64
 20  Recorded_Speed_kmh                   200000 non-null  float64
 21  Baseline_Expected_Response_Time_min  200000 non-null  float64
 22  Accident_Occurred                    200000 non-null  int64
 23  Collision_Type                       8231 non-null    object
 24  Vehicles_Involved                    200000 non-null  int64
 25  Accident_Severity                    200000 non-null  object
 26  Dispatch_Priority                    8231 non-null    object
 27  Actual_Response_Time_min             200000 non-null  float64
 28  Road_Closure_Duration_min            200000 non-null  float64
dtypes: float64(9), int64(6), object(14)
memory usage: 44.3+ MB

## Second Pair

Looking into the data, there appears to be no accidents, yet there are collisions in the Collision_Type column as well as dispatches in the Dispatch_Priority column but in the Accident_Occurred column we just see 200000 and that it is non-null with an int64 data type. We can check the value of accidents by using the sum method. Which shows us 8231 to match the Collision_type and Dispatch_Priority values.

In [4]:
total_accident_occurred = df['Accident_Occurred'].sum()
print(total_accident_occurred)

8231

I created a variable to put into a dataframe the instances where an accident occurred is True, i printed it out which just showed me the Boolean Values of True or False.

In [5]:
Accidents = df['Accident_Occurred']==1
print(Accidents)

0         False
1         False
2         False
3         False
4         False
          ...
199995    False
199996    False
199997    False
199998    False
199999    False
Name: Accident_Occurred, Length: 200000, dtype: bool

By taking it one step further, I put df[Accidents] to see the dataframe I just created in the previous step and now I can see the rows where an accident occurred, which shows up as a value of 1 and at the bottom we can see that there are 8231 rows which match the number of Collision_Type and Dispatch_Priority values.

In [6]:
df[Accidents]

,Record_ID,Timestamp,Date,Hour,Month,Day_of_Week,Time_of_Day,Is_Holiday,Area_Type,Road_Type,...,Vehicle_Age_yrs,Recorded_Speed_kmh,Baseline_Expected_Response_Time_min,Accident_Occurred,Collision_Type,Vehicles_Involved,Accident_Severity,Dispatch_Priority,Actual_Response_Time_min,Road_Closure_Duration_min
22,REC_0000022,2022-06-20 19:58:02.379995627,2022-06-20,19,6,Monday,Evening Peak,1,Suburban,Interstate,...,1.6,76.300000,9.7,1,Rear-End,2,Minor,Standard,24.7,117.6
34,REC_0000034,2025-05-06 13:17:48.647194458,2025-05-06,13,5,Tuesday,Midday,0,Rural,Interstate,...,11.3,112.700000,25.0,1,Rear-End,2,Severe,High,36.4,524.7
40,REC_0000040,2022-02-22 11:32:41.147567083,2022-02-22,11,2,Tuesday,Midday,0,Urban,Local,...,2.6,15.300000,3.0,1,Rear-End,2,Minor,Standard,14.3,143.2
44,REC_0000044,2022-12-13 09:19:46.322607147,2022-12-13,9,12,Tuesday,Morning Peak,0,Urban,Collector,...,1.8,20.500000,5.2,1,Rear-End,2,Minor,Standard,17.6,167.2
57,REC_0000057,2024-10-11 06:59:41.895988143,2024-10-11,6,10,Friday,Morning Peak,0,Urban,Arterial,...,0.5,32.000000,6.7,1,Rear-End,2,Severe,Medium,13.0,348.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199934,REC_N0000333,2024-01-17 19:25:26.871356961,2024-01-17,19,1,Wednesday,Evening Peak,0,Urban,Local,...,6.4,13.603869,9.7,1,Rear-End,2,Moderate,High,23.4,339.5
199938,REC_N0000337,2025-04-02 00:02:56.727309477,2025-04-02,0,4,Wednesday,Night,0,Suburban,Collector,...,14.3,40.548504,13.1,1,Head-On,2,Moderate,High,13.1,210.6
199948,REC_N0000347,2023-08-04 09:20:20.566421950,2023-08-04,9,8,Friday,Morning Peak,0,Suburban,Interstate,...,6.4,64.566518,12.9,1,Rear-End,2,Minor,Standard,25.7,150.4
199961,REC_N0000360,2022-05-03 13:25:03.854892382,2022-05-03,13,5,Tuesday,Midday,0,Suburban,Interstate,...,2.6,86.135530,12.6,1,Rear-End,2,Minor,Standard,17.0,104.6
199972,REC_N0000371,2023-02-20 09:48:26.510294896,2023-02-20,9,2,Monday,Morning Peak,1,Suburban,Collector,...,4.8,35.453525,14.7,1,Single-Vehicle,1,Minor,Standard,21.3,189.1

## Third pair

The dataset does not indicate the years of data collected so referring back to a previous assignment to display the first couple of rows and the last but in ascending order so we can see the range of years we are working with. By running the code we can see the date range is from: Jan 1, 2022 to Dec 31, 2025

In [7]:
pd.concat([df.sort_values('Date', ascending=False).head(5),
df.sort_values('Date', ascending=False).tail(5)])

,Record_ID,Timestamp,Date,Hour,Month,Day_of_Week,Time_of_Day,Is_Holiday,Area_Type,Road_Type,...,Vehicle_Age_yrs,Recorded_Speed_kmh,Baseline_Expected_Response_Time_min,Accident_Occurred,Collision_Type,Vehicles_Involved,Accident_Severity,Dispatch_Priority,Actual_Response_Time_min,Road_Closure_Duration_min
196316,REC_0196316,2025-12-31 23:00:47.707162710,2025-12-31,23,12,Wednesday,Night,0,Urban,Local,...,2.7,28.8,6.9,0,NaN,0,No Accident,NaN,0.0,0.0
174617,REC_0174617,2025-12-31 08:43:47.257282495,2025-12-31,8,12,Wednesday,Morning Peak,0,Urban,Local,...,3.9,18.0,7.1,0,NaN,0,No Accident,NaN,0.0,0.0
3915,REC_0003915,2025-12-31 10:49:05.828038543,2025-12-31,10,12,Wednesday,Midday,0,Suburban,Local,...,10.9,38.8,12.2,0,NaN,0,No Accident,NaN,0.0,0.0
144563,REC_0144563,2025-12-31 05:51:06.256162322,2025-12-31,5,12,Wednesday,Night,0,Urban,Interstate,...,1.5,83.2,8.5,0,NaN,0,No Accident,NaN,0.0,0.0
73061,REC_0073061,2025-12-31 22:10:24.885089174,2025-12-31,22,12,Wednesday,Night,0,Suburban,Arterial,...,2.4,48.6,10.4,0,NaN,0,No Accident,NaN,0.0,0.0
41088,REC_0041088,2022-01-01 17:49:23.607043320,2022-01-01,17,1,Saturday,Evening Peak,0,Suburban,Local,...,8.0,30.4,14.0,0,NaN,0,No Accident,NaN,0.0,0.0
155043,REC_0155043,2022-01-01 04:50:12.758365381,2022-01-01,4,1,Saturday,Night,0,Urban,Local,...,5.9,22.4,5.7,0,NaN,0,No Accident,NaN,0.0,0.0
179079,REC_0179079,2022-01-01 07:21:41.674084167,2022-01-01,7,1,Saturday,Morning Peak,0,Suburban,Arterial,...,11.1,54.0,11.9,0,NaN,0,No Accident,NaN,0.0,0.0
50645,REC_0050645,2022-01-01 12:45:47.734668121,2022-01-01,12,1,Saturday,Midday,0,Suburban,Collector,...,10.1,57.3,14.1,0,NaN,0,No Accident,NaN,0.0,0.0
39846,REC_0039846,2022-01-01 17:05:44.341413942,2022-01-01,17,1,Saturday,Evening Peak,0,Suburban,Collector,...,5.5,27.2,14.2,0,NaN,0,No Accident,NaN,0.0,0.0

## Fourth Pair

Use the describe() method to display statistical information for the numeric columns in the DataFrame. Start by coding this statement without the T property. Then, add the T property to see how the display changes.

In [8]:
df.describe()

,Hour,Month,Is_Holiday,Speed_Limit_kmh,Visibility_m,Congestion_Index,Driver_Age,Driver_Experience_yrs,Vehicle_Age_yrs,Recorded_Speed_kmh,Baseline_Expected_Response_Time_min,Accident_Occurred,Vehicles_Involved,Actual_Response_Time_min,Road_Closure_Duration_min
count,200000.000000,200000.000000,200000.000000,200000.000000,194907.000000,200000.000000,200000.000000,196004.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,12.222835,6.537395,0.032105,57.466350,6463.122449,55.640682,38.352715,10.610108,6.980861,49.598011,12.382128,0.041155,0.086390,0.903586,7.657380
std,5.510585,3.448349,0.176279,26.353645,4539.026103,28.715893,13.289605,7.796178,4.770430,31.917212,5.491076,0.198649,0.446338,4.661588,47.600793
min,0.000000,1.000000,0.000000,30.000000,66.400000,2.200000,16.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000
25%,8.000000,4.000000,0.000000,30.000000,1737.350000,31.600000,29.000000,4.700000,3.400000,30.400000,8.400000,0.000000,0.000000,0.000000,0.000000
50%,12.000000,7.000000,0.000000,50.000000,7948.600000,53.700000,38.000000,9.400000,6.100000,43.900000,11.000000,0.000000,0.000000,0.000000,0.000000
75%,17.000000,10.000000,0.000000,80.000000,10392.800000,79.100000,47.000000,15.200000,9.400000,62.200000,14.300000,0.000000,0.000000,0.000000,0.000000
max,23.000000,12.000000,1.000000,120.000000,15000.000000,100.000000,85.000000,59.000000,30.000000,999.000000,29.600000,1.000000,5.000000,56.600000,1772.500000

Now the describe method with the T property

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Hour,200000.0,12.222835,5.510585,0.0,8.00,12.0,17.0,23.0
Month,200000.0,6.537395,3.448349,1.0,4.00,7.0,10.0,12.0
Is_Holiday,200000.0,0.032105,0.176279,0.0,0.00,0.0,0.0,1.0
Speed_Limit_kmh,200000.0,57.466350,26.353645,30.0,30.00,50.0,80.0,120.0
Visibility_m,194907.0,6463.122449,4539.026103,66.4,1737.35,7948.6,10392.8,15000.0
Congestion_Index,200000.0,55.640682,28.715893,2.2,31.60,53.7,79.1,100.0
Driver_Age,200000.0,38.352715,13.289605,16.0,29.00,38.0,47.0,85.0
Driver_Experience_yrs,196004.0,10.610108,7.796178,0.0,4.70,9.4,15.2,59.0
Vehicle_Age_yrs,200000.0,6.980861,4.770430,0.0,3.40,6.1,9.4,30.0
Recorded_Speed_kmh,200000.0,49.598011,31.917212,0.0,30.40,43.9,62.2,999.0
Baseline_Expected_Response_Time_min,200000.0,12.382128,5.491076,3.0,8.40,11.0,14.3,29.6
Accident_Occurred,200000.0,0.041155,0.198649,0.0,0.00,0.0,0.0,1.0
Vehicles_Involved,200000.0,0.086390,0.446338,0.0,0.00,0.0,0.0,5.0
Actual_Response_Time_min,200000.0,0.903586,4.661588,0.0,0.00,0.0,0.0,56.6
Road_Closure_Duration_min,200000.0,7.657380,47.600793,0.0,0.00,0.0,0.0,1772.5

## Fifth Pair

One of our older assignments has us using the nunique() method. I ran it and round it interesting that the Record_ID and Timestamp had 199403 when i was expecting 200000 as shown from using dinfo().

In [10]:
df.nunique()

Record_ID                              199403
Timestamp                              199403
Date                                     1461
Hour                                       24
Month                                      12
Day_of_Week                                 7
Time_of_Day                                 4
Is_Holiday                                  2
Area_Type                                   3
Road_Type                                   4
Intersection_Type                           3
Speed_Limit_kmh                             8
Weather                                     7
Road_Condition                              5
Visibility_m                            82142
Congestion_Index                         1347
Vehicle_Type                                5
Driver_Age                                 70
Driver_Experience_yrs                     482
Vehicle_Age_yrs                           301
Recorded_Speed_kmh                       1986
Baseline_Expected_Response_Time_min       265
Accident_Occurred                           2
Collision_Type                              4
Vehicles_Involved                           6
Accident_Severity                           5
Dispatch_Priority                           3
Actual_Response_Time_min                  435
Road_Closure_Duration_min                2794
dtype: int64

## Reflection Question

"Why did you choose the downloaded dataset?"

I chose this dataset because it relates to data that would be used to help analyze and solve real world probems. Rather than pick any old dataset like "Wine Reviews", which was also on Kaggle, I wanted to use a dataset that one would typically see in the workplace with lots of real world data and possibly even messy as this would give a real example of what its like in a job that relates to performing such analysis. Even in the description it mentioned that this dataset was designed for developing, testing, and benchmarking predictive modeling pipelines. So choosing this dataset to me was a no brainer and if needed to use again for a future assignment I would choose this dataset again.